# site properties and page defaults
title: LIMB Lab
subtitle: Locomotion & Imaging for Musculoskeletal Biomechanics
description: Welcome to the LIMB Lab! We specialize in investigations of how joint biomechanics, physical activity, and kinematics contribute to the onset and progression of musculoskeletal diseases such as osteoarthritis.
header: images/logos/DF_background.jpg
footer: images/logos/DF_background.jpg
proofer: false

# site social media and other links
links:
  email: koren.roach@ucalgary.ca
#  orcid: 0000-0001-8713-9213
  google-scholar: CCjfN8MAAAAJ
#  github: justen-saini
#  twitter: justen-saini
#  youtube: justen-saini

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
